/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gestion_demande_visa.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Demande service. Represents a row in the &quot;GDV_Demande&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.gestion_demande_visa.model.impl.DemandeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.gestion_demande_visa.model.impl.DemandeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Demande
 * @generated
 */
@ProviderType
public interface DemandeModel extends BaseModel<Demande>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a demande model instance should use the {@link Demande} interface instead.
	 */

	/**
	 * Returns the primary key of this demande.
	 *
	 * @return the primary key of this demande
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this demande.
	 *
	 * @param primaryKey the primary key of this demande
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the demande ID of this demande.
	 *
	 * @return the demande ID of this demande
	 */
	public long getDemandeId();

	/**
	 * Sets the demande ID of this demande.
	 *
	 * @param demandeId the demande ID of this demande
	 */
	public void setDemandeId(long demandeId);

	/**
	 * Returns the group ID of this demande.
	 *
	 * @return the group ID of this demande
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this demande.
	 *
	 * @param groupId the group ID of this demande
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this demande.
	 *
	 * @return the company ID of this demande
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this demande.
	 *
	 * @param companyId the company ID of this demande
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this demande.
	 *
	 * @return the user ID of this demande
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this demande.
	 *
	 * @param userId the user ID of this demande
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this demande.
	 *
	 * @return the user uuid of this demande
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this demande.
	 *
	 * @param userUuid the user uuid of this demande
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this demande.
	 *
	 * @return the create date of this demande
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this demande.
	 *
	 * @param createDate the create date of this demande
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this demande.
	 *
	 * @return the modified date of this demande
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this demande.
	 *
	 * @param modifiedDate the modified date of this demande
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the destination of this demande.
	 *
	 * @return the destination of this demande
	 */
	@AutoEscape
	public String getDestination();

	/**
	 * Sets the destination of this demande.
	 *
	 * @param destination the destination of this demande
	 */
	public void setDestination(String destination);

	/**
	 * Returns the visa type of this demande.
	 *
	 * @return the visa type of this demande
	 */
	@AutoEscape
	public String getVisaType();

	/**
	 * Sets the visa type of this demande.
	 *
	 * @param visaType the visa type of this demande
	 */
	public void setVisaType(String visaType);

	/**
	 * Returns the trip date of this demande.
	 *
	 * @return the trip date of this demande
	 */
	public Date getTripDate();

	/**
	 * Sets the trip date of this demande.
	 *
	 * @param tripDate the trip date of this demande
	 */
	public void setTripDate(Date tripDate);

	/**
	 * Returns the trip purpse of this demande.
	 *
	 * @return the trip purpse of this demande
	 */
	@AutoEscape
	public String getTripPurpse();

	/**
	 * Sets the trip purpse of this demande.
	 *
	 * @param tripPurpse the trip purpse of this demande
	 */
	public void setTripPurpse(String tripPurpse);

	/**
	 * Returns the stay duration of this demande.
	 *
	 * @return the stay duration of this demande
	 */
	@AutoEscape
	public String getStayDuration();

	/**
	 * Sets the stay duration of this demande.
	 *
	 * @param stayDuration the stay duration of this demande
	 */
	public void setStayDuration(String stayDuration);

	/**
	 * Returns the passport of this demande.
	 *
	 * @return the passport of this demande
	 */
	public long getPassport();

	/**
	 * Sets the passport of this demande.
	 *
	 * @param passport the passport of this demande
	 */
	public void setPassport(long passport);

	/**
	 * Returns the photo of this demande.
	 *
	 * @return the photo of this demande
	 */
	public long getPhoto();

	/**
	 * Sets the photo of this demande.
	 *
	 * @param photo the photo of this demande
	 */
	public void setPhoto(long photo);

	/**
	 * Returns the flight reservation of this demande.
	 *
	 * @return the flight reservation of this demande
	 */
	public long getFlightReservation();

	/**
	 * Sets the flight reservation of this demande.
	 *
	 * @param flightReservation the flight reservation of this demande
	 */
	public void setFlightReservation(long flightReservation);

	/**
	 * Returns the statue of this demande.
	 *
	 * @return the statue of this demande
	 */
	@AutoEscape
	public String getStatue();

	/**
	 * Sets the statue of this demande.
	 *
	 * @param statue the statue of this demande
	 */
	public void setStatue(String statue);

}